// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjv5spIpvbSWpcrpW3aO76oogsrNsXOM',
    appId: '1:149804457186:android:9830a48ac9e6b5745152bb',
    messagingSenderId: '149804457186',
    projectId: 'codefee-6b8ef',
    databaseURL: 'https://codefee-6b8ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codefee-6b8ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjvXsL5MwMKxmQZavgL-y7WuZSF5X6X8',
    appId: '1:149804457186:ios:dbfca4adf10391d65152bb',
    messagingSenderId: '149804457186',
    projectId: 'codefee-6b8ef',
    databaseURL: 'https://codefee-6b8ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codefee-6b8ef.appspot.com',
    androidClientId: '149804457186-9jq02h0ocvlu7fh1h18valuva9lssfh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypuser',
  );
}
